mixed-port: 7890
redir-port: 7892
allow-lan: true
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9090
external-ui: dashboard
secret: ""

dns:
  enable: true
  listen: 0.0.0.0:1053
  fake-ip-range: 198.18.0.1/16
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    # - tls://dns.rubyfish.cn:853
  fallback:
    - https://dns.google/dns-query
    - tls://1.1.1.1
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

#tun:
#  enable: true
#  stack: system
#  dns-hijack: 
#    - tcp://8.8.8.8:53

interface-name: en0

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - AUTO
    use:
      - my_provider
  - name: AUTO
    use:
      - my_provider
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
  - name: 国内站点
    type: select
    proxies:
      - DIRECT

proxy-providers:
  my_provider:
    type: file
    path: ./proxies.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204

rule-providers:
  my_proxy_rules:
    type: file
    behavior: classical
    path: ./my_proxy_rules.yaml
  my_direct_rules:
    type: file
    behavior: classical
    path: ./my_direct_rules.yaml

rules:
  - RULE-SET,my_direct_rules,DIRECT
  - GEOIP,CN,国内站点
  - RULE-SET,my_proxy_rules,PROXY
  - MATCH,PROXY
